"""
Generate performance tables and statistical analysis from experimental results.
Reads CSV files generated by performance-test.mjs and produces formatted tables
for LaTeX/paper inclusion.
"""

import pandas as pd
import numpy as np
import sys
from pathlib import Path
from stats import (
    kruskal_wallis_test,
    dunn_test,
    pairwise_cliffs_delta,
    calculate_summary_statistics,
)

# Metrics to analyze (nomes das colunas no CSV - exatamente como aparecem)
METRICS = [
    "LCP (s)",
    "FCP (s)",
    "SI (s)",
    "TTI (s)",
    "CLS (s)",
    "FID (ms)",
    "Score",
    "JS Heap Used Size (Kb)",
]

# Metric display names for tables
METRIC_NAMES = {
    "LCP (s)": "LCP (s)",
    "FCP (s)": "FCP (s)",
    "SI (s)": "SI (s)",
    "TTI (s)": "TTI (s)",
    "CLS (s)": "CLS (s)",
    "FID (ms)": "FID (ms)",
    "Score": "Performance Score",
    "JS Heap Used Size (Kb)": "JS Heap Used (KB)",
}

# Mapeamento de nomes curtos para nomes completos (para arquivos de saída)
METRIC_SHORT_NAMES = {
    "LCP (s)": "LCP",
    "FCP (s)": "FCP",
    "SI (s)": "SI",
    "TTI (s)": "TTI",
    "CLS (s)": "CLS",
    "FID (ms)": "FID",
    "Score": "Score",
    "JS Heap Used Size (Kb)": "JSHeapUsedSize",
}


def load_data(csv_path):
    """Load experimental data from CSV file."""
    df = pd.read_csv(csv_path)
    # Normalizar nomes das colunas principais para minúsculas
    df = df.rename(columns={
        "Format": "format",
        "Size": "size",
        "Minify": "minify",
        "Gzip": "gzip",
    })
    return df


def create_group_name(row):
    """Create a group identifier from experimental factors."""
    parts = [row["format"].upper()]
    if row["format"] == "json":
        parts.append(f"minify{row['minify']}")
    parts.append(f"gzip{row['gzip']}")
    return "-".join(parts)


def format_number(value, decimals=3):
    """Format number for LaTeX table."""
    if pd.isna(value):
        return "---"
    if abs(value) < 0.001:
        return f"${value:.2e}$"
    return f"${value:.{decimals}f}$"


def generate_summary_table(df, metric, output_dir):
    """Generate summary statistics table for a metric."""
    # Group by experimental factors
    groups = []
    group_names = []
    
    for size in df["size"].unique():
        for format_type in df["format"].unique():
            for minify in df["minify"].unique():
                for gzip in df["gzip"].unique():
                    mask = (
                        (df["size"] == size)
                        & (df["format"] == format_type)
                        & (df["minify"] == minify)
                        & (df["gzip"] == gzip)
                    )
                    
                    # Skip if minify is set for HTML format
                    if format_type == "html" and minify == 1:
                        continue
                    
                    group_data = df[mask][metric].values
                    if len(group_data) > 0:
                        groups.append(group_data)
                        group_name = f"{size}-{create_group_name(df[mask].iloc[0])}"
                        group_names.append(group_name)
    
    if len(groups) == 0:
        print(f"No data for metric {metric}")
        return None
    
    summary_df = calculate_summary_statistics(groups, group_names)
    
    # Format for LaTeX
    summary_df["mean_std"] = (
        summary_df["mean"].apply(lambda x: f"{x:.3f}")
        + " ± "
        + summary_df["std"].apply(lambda x: f"{x:.3f}")
    )
    summary_df["median_iqr"] = (
        summary_df["median"].apply(lambda x: f"{x:.3f}")
        + " ["
        + summary_df["q25"].apply(lambda x: f"{x:.3f}")
        + ", "
        + summary_df["q75"].apply(lambda x: f"{x:.3f}")
        + "]"
    )
    
    # Save CSV
    metric_short = METRIC_SHORT_NAMES.get(metric, metric.replace(" ", "_").replace("(", "").replace(")", ""))
    csv_path = output_dir / f"summary_{metric_short}.csv"
    summary_df.to_csv(csv_path, index=False)
    
    # Generate LaTeX table
    latex_cols = ["group", "mean_std", "median_iqr", "n"]
    latex_df = summary_df[latex_cols].copy()
    latex_df.columns = ["Group", "Mean ± SD", "Median [Q1, Q3]", "N"]
    
    latex_path = output_dir / f"summary_{metric_short}.tex"
    try:
        with open(latex_path, "w") as f:
            f.write(latex_df.to_latex(index=False, escape=False, float_format="%.3f"))
    except Exception as e:
        print(f"  Warning: Could not generate LaTeX table: {e}")
    
    print(f"Generated summary table for {metric}: {csv_path}")
    return summary_df


def generate_kruskal_wallis_results(df, metric, output_dir):
    """Generate Kruskal-Wallis test results for a metric."""
    results = []
    
    # Test for each size separately
    for size in df["size"].unique():
        df_size = df[df["size"] == size]
        
        groups = []
        group_names = []
        
        for format_type in df_size["format"].unique():
            for minify in df_size["minify"].unique():
                for gzip in df_size["gzip"].unique():
                    mask = (
                        (df_size["format"] == format_type)
                        & (df_size["minify"] == minify)
                        & (df_size["gzip"] == gzip)
                    )
                    
                    if format_type == "html" and minify == 1:
                        continue
                    
                    group_data = df_size[mask][metric].values
                    if len(group_data) > 0:
                        groups.append(group_data)
                        group_names.append(create_group_name(df_size[mask].iloc[0]))
        
        if len(groups) >= 2:
            statistic, pvalue = kruskal_wallis_test(groups)
            results.append({
                "size": size,
                "metric": metric,
                "statistic": statistic,
                "pvalue": pvalue,
                "significant": pvalue < 0.05 if not pd.isna(pvalue) else False,
            })
    
    if not results:
        return None
    
    results_df = pd.DataFrame(results)
    
    metric_short = METRIC_SHORT_NAMES.get(metric, metric.replace(" ", "_").replace("(", "").replace(")", ""))
    csv_path = output_dir / f"kruskal_wallis_{metric_short}.csv"
    results_df.to_csv(csv_path, index=False)
    
    print(f"Generated Kruskal-Wallis results for {metric}: {csv_path}")
    return results_df


def generate_dunn_results(df, metric, output_dir):
    """Generate Dunn's post-hoc test results for a metric."""
    all_results = []
    
    for size in df["size"].unique():
        df_size = df[df["size"] == size]
        
        groups = []
        group_names = []
        
        for format_type in df_size["format"].unique():
            for minify in df_size["minify"].unique():
                for gzip in df_size["gzip"].unique():
                    mask = (
                        (df_size["format"] == format_type)
                        & (df_size["minify"] == minify)
                        & (df_size["gzip"] == gzip)
                    )
                    
                    if format_type == "html" and minify == 1:
                        continue
                    
                    group_data = df_size[mask][metric].values
                    if len(group_data) > 0:
                        groups.append(group_data)
                        group_names.append(create_group_name(df_size[mask].iloc[0]))
        
        if len(groups) >= 2:
            dunn_df = dunn_test(groups, group_names, method="holm")
            if not dunn_df.empty:
                dunn_df["size"] = size
                dunn_df["metric"] = metric
                all_results.append(dunn_df)
    
    if not all_results:
        return None
    
    results_df = pd.concat(all_results, ignore_index=True)
    
    metric_short = METRIC_SHORT_NAMES.get(metric, metric.replace(" ", "_").replace("(", "").replace(")", ""))
    csv_path = output_dir / f"dunn_{metric_short}.csv"
    results_df.to_csv(csv_path, index=False)
    
    print(f"Generated Dunn's test results for {metric}: {csv_path}")
    return results_df


def generate_cliffs_delta_results(df, metric, output_dir):
    """Generate Cliff's Delta effect size results for a metric."""
    all_results = []
    
    for size in df["size"].unique():
        df_size = df[df["size"] == size]
        
        groups = []
        group_names = []
        
        for format_type in df_size["format"].unique():
            for minify in df_size["minify"].unique():
                for gzip in df_size["gzip"].unique():
                    mask = (
                        (df_size["format"] == format_type)
                        & (df_size["minify"] == minify)
                        & (df_size["gzip"] == gzip)
                    )
                    
                    if format_type == "html" and minify == 1:
                        continue
                    
                    group_data = df_size[mask][metric].values
                    if len(group_data) > 0:
                        groups.append(group_data)
                        group_names.append(create_group_name(df_size[mask].iloc[0]))
        
        if len(groups) >= 2:
            cliffs_df = pairwise_cliffs_delta(groups, group_names)
            if not cliffs_df.empty:
                cliffs_df["size"] = size
                cliffs_df["metric"] = metric
                all_results.append(cliffs_df)
    
    if not all_results:
        return None
    
    results_df = pd.concat(all_results, ignore_index=True)
    
    metric_short = METRIC_SHORT_NAMES.get(metric, metric.replace(" ", "_").replace("(", "").replace(")", ""))
    csv_path = output_dir / f"cliffs_delta_{metric_short}.csv"
    results_df.to_csv(csv_path, index=False)
    
    print(f"Generated Cliff's Delta results for {metric}: {csv_path}")
    return results_df


def main():
    """Main function to generate all tables."""
    if len(sys.argv) < 2:
        print("Usage: python make_tables.py <input_csv_path> [output_dir]")
        sys.exit(1)
    
    input_csv = Path(sys.argv[1])
    output_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("tables")
    
    if not input_csv.exists():
        print(f"Error: Input file {input_csv} not found")
        sys.exit(1)
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"Loading data from {input_csv}")
    df = load_data(input_csv)
    print(f"Loaded {len(df)} rows")
    
    print(f"\nGenerating tables in {output_dir}")
    
    for metric in METRICS:
        # Normalizar nome da coluna (remover espaços extras)
        metric_col = metric
        if metric_col not in df.columns:
            # Tentar variações do nome
            possible_names = [metric_col, metric_col.replace(" ", ""), metric_col.replace(" (s)", ""), metric_col.replace(" (ms)", "")]
            found = False
            for name in possible_names:
                if name in df.columns:
                    metric_col = name
                    found = True
                    break
            if not found:
                print(f"Warning: Metric {metric} not found in data, skipping")
                continue
        
        print(f"\nProcessing {metric} ({METRIC_NAMES.get(metric, metric)})...")
        
        # Summary statistics
        generate_summary_table(df, metric_col, output_dir)
        
        # Kruskal-Wallis test
        generate_kruskal_wallis_results(df, metric_col, output_dir)
        
        # Dunn's post-hoc test
        generate_dunn_results(df, metric_col, output_dir)
        
        # Cliff's Delta
        generate_cliffs_delta_results(df, metric_col, output_dir)
    
    print(f"\nAll tables generated in {output_dir}")


if __name__ == "__main__":
    main()

